# Use our own docker image, that was generated and pushed with the following commands:
#   docker login registry.gitlab.inria.fr
#   docker build -t registry.gitlab.inria.fr/quinson/mbi2 .
#   docker push registry.gitlab.inria.fr/quinson/mbi2
# image: registry.gitlab.com/mwapl/benchmarking-mpi:latest
image: registry.gitlab.inria.fr/quinson/mbi2:latest

variables:
    GIT_SUBMODULE_STRATEGY: none

stages:
    - build
    - test
    - svg
    - gather

codes:
    stage: build
    needs: []
    script:
        - mkdir gencodes; cd gencodes;for g in $(ls ../scripts/*Generator.py) ; do $g; done
    artifacts:
        untracked: false
        expire_in: 30 days
        when: always
        paths:
            - gencodes

build-must:
    stage: build
    needs: []
    script:
        - scripts/MUST-build
    artifacts:
        untracked: false
        expire_in: 30 days
        paths:
            - builds/MUST

test-must-1:
    stage: test
    needs:
        - job: build-must
          artifacts: true
        - job: codes
          artifacts: true
    before_script:
        - apt-get install -y psmisc
    script:
        - ./MBI.py -x must -b 1/10
    artifacts:
        untracked: false
        expire_in: 30 days
        when: always
        paths:
            - logs

test-must-2:
    stage: test
    needs:
        - job: build-must
          artifacts: true
        - job: codes
          artifacts: true
    before_script:
        - apt-get install -y psmisc
    script:
        - ./MBI.py -x must -b 2/10
    artifacts:
        untracked: false
        expire_in: 30 days
        when: always
        paths:
            - logs

test-must-3:
    stage: test
    needs:
        - job: build-must
          artifacts: true
        - job: codes
          artifacts: true
    before_script:
        - apt-get install -y psmisc
    script:
        - ./MBI.py -x must -b 3/10
    artifacts:
        untracked: false
        expire_in: 30 days
        when: always
        paths:
            - logs

test-must-4:
    stage: test
    needs:
        - job: build-must
          artifacts: true
        - job: codes
          artifacts: true
    before_script:
        - apt-get install -y psmisc
    script:
        - ./MBI.py -x must -b 4/10
    artifacts:
        untracked: false
        expire_in: 30 days
        when: always
        paths:
            - logs

test-must-5:
    stage: test
    needs:
        - job: build-must
          artifacts: true
        - job: codes
          artifacts: true
    before_script:
        - apt-get install -y psmisc
    script:
        - ./MBI.py -x must -b 5/10
    artifacts:
        untracked: false
        expire_in: 30 days
        when: always
        paths:
            - logs

test-must-6:
    stage: test
    needs:
        - job: build-must
          artifacts: true
        - job: codes
          artifacts: true
    before_script:
        - apt-get install -y psmisc
    script:
        - ./MBI.py -x must -b 6/10
    artifacts:
        untracked: false
        expire_in: 30 days
        when: always
        paths:
            - logs

test-must-7:
    stage: test
    needs:
        - job: build-must
          artifacts: true
        - job: codes
          artifacts: true
    before_script:
        - apt-get install -y psmisc
    script:
        - ./MBI.py -x must -b 7/10
    artifacts:
        untracked: false
        expire_in: 30 days
        when: always
        paths:
            - logs

test-must-8:
    stage: test
    needs:
        - job: build-must
          artifacts: true
        - job: codes
          artifacts: true
    before_script:
        - apt-get install -y psmisc
    script:
        - ./MBI.py -x must -b 8/10
    artifacts:
        untracked: false
        expire_in: 30 days
        when: always
        paths:
            - logs

test-must-9:
    stage: test
    needs:
        - job: build-must
          artifacts: true
        - job: codes
          artifacts: true
    before_script:
        - apt-get install -y psmisc
    script:
        - ./MBI.py -x must -b 9/10
    artifacts:
        untracked: false
        expire_in: 30 days
        when: always
        paths:
            - logs

test-must-10:
    stage: test
    needs:
        - job: build-must
          artifacts: true
        - job: codes
          artifacts: true
    before_script:
        - apt-get install -y psmisc
    script:
        - ./MBI.py -x must -b 10/10
    artifacts:
        untracked: false
        expire_in: 30 days
        when: always
        paths:
            - logs

build-aislinn:
    stage: build
    needs: []
    image: ubuntu:18.04
    before_script:
        - apt-get update
        - apt-get install -y gcc python2.7 python3.8 python-jinja2 autotools-dev automake build-essential git
    script:
        - ./scripts/Aislinn-build
    artifacts:
        untracked: false
        expire_in: 30 days
        when: always
        paths:
            - tools/aislinn-git/*

test-aislinn:
    stage: test
    image: ubuntu:18.04
    needs:
        - job: build-aislinn
          artifacts: true
        - job: codes
          artifacts: true
    script:
        - ./MBI.py -x aislinn
    artifacts:
        untracked: false
        expire_in: 30 days
        when: always
        paths:
            - logs

# MPI-SV is already built on its image file
# build-mpisv:
#    stage: build
#    needs: []
#    image: mpisv/mpi-sv
#    script:
#        - ./scripts/mpisv-build
#    artifacts:
#        untracked: false
#        expire_in: 30 days
#        when: always
#        paths:
#            - tools/mpisv

# MPI-SV refuses to build on nested virtualization as we have when using docker on gitlab-CI
# test-mpisv:
#    stage: test
#    image: mpisv/mpi-sv
#    needs:
##        - job: build-mpisv
##          artifacts: true
#        - job: codes
#          artifacts: true
#    script:
#        - ./MBI.py -x mpisv
#    artifacts:
#        untracked: false
#        expire_in: 30 days
#        when: always
#        paths:
#            - logs

build-civl:
    stage: build
    needs: []
    script:
        - ./scripts/CIVL-build
    artifacts:
        untracked: false
        expire_in: 30 days
        when: always
        paths:
            - tools/CIVL*

test-civl-1:
    stage: test
    needs:
        - job: build-civl
          artifacts: false
        - job: codes
          artifacts: true
    script:
        - ./MBI.py -x civl -b 1/3
    artifacts:
        untracked: false
        expire_in: 30 days
        when: always
        paths:
            - logs
test-civl-2:
    stage: test
    needs:
        - job: build-civl
          artifacts: false
        - job: codes
          artifacts: true
    script:
        - ./MBI.py -x civl -b 2/3
    artifacts:
        untracked: false
        expire_in: 30 days
        when: always
        paths:
            - logs
test-civl-3:
    stage: test
    needs:
        - job: build-civl
          artifacts: false
        - job: codes
          artifacts: true
    script:
        - ./MBI.py -x civl -b 3/3
    artifacts:
        untracked: false
        expire_in: 30 days
        when: always
        paths:
            - logs

build-parcoach:
    stage: build
    needs: []
    script:
        - ./scripts/Parcoach-build
    artifacts:
        untracked: false
        expire_in: 30 days
        when: always
        paths:
            - builds/parcoach/*

test-parcoach:
    stage: test
    needs:
        - job: build-parcoach
          artifacts: true
        - job: codes
          artifacts: true
    script:
        - ./MBI.py -x parcoach
    artifacts:
        untracked: false
        expire_in: 30 days
        when: always
        paths:
            - logs

build-simgrid:
    stage: build
    needs: []
    script:
        - ./scripts/SimGrid-build
    cache:
        paths:
            - SimGrid/*
    artifacts:
        untracked: false
        expire_in: 30 days
        when: always
        paths:
            - builds/SimGrid

test-simgrid:
    stage: test
    needs:
        - job: build-simgrid
          artifacts: true
        - job: codes
          artifacts: true
    script:
        - ./MBI.py -x simgrid
    artifacts:
        untracked: false
        expire_in: 30 days
        when: always
        paths:
            - logs

build-isp:
    stage: build
    needs: []
    script:
        - sh -x ./scripts/ISP-build
    artifacts:
        untracked: false
        expire_in: 30 days
        when: always
        paths:
            - ./builds/ISP

test-isp:
    stage: test
    needs:
        - job: build-isp
          artifacts: true
        - job: codes
          artifacts: true
    script:
        - ./MBI.py -x isp
    artifacts:
        untracked: false
        expire_in: 30 days
        when: always
        paths:
            - logs

simgrid-svg:
    stage: svg
    needs:
        - job: test-simgrid
          artifacts: true
    # before_script:
    #   - apt-get update
    #   - apt-get install -y python3-pip libcairo2
    #   - pip3 install drawSvg
    script:
        - cd Data
        - python3.8 gen_svg.py -i ../logs/simgrid/bench_simgrid.csv -o simgrid_result_LOG --header false
        - cp *svg ../logs/
    artifacts:
        untracked: false
        expire_in: 30 days
        when: always
        paths:
            - logs/*

parcoach-svg:
    stage: svg
    needs:
        - job: test-parcoach
          artifacts: true
    # before_script:
    #   - apt-get update
    #   - apt-get install -y python3-pip libcairo2
    #   - pip3 install drawSvg
    script:
        - cd Data
        - python3.8 gen_svg.py -i ../logs/parcoach/bench_parcoach.csv -o parcoach_result_LOG --header false
        - cp *svg ../logs/
    artifacts:
        untracked: false
        expire_in: 30 days
        when: always
        paths:
            - logs/*

isp-svg:
    stage: svg
    needs:
        - job: test-isp
          artifacts: true
    # before_script:
    #   - apt-get update
    #   - apt-get install -y python3-pip libcairo2
    #   - pip3 install drawSvg
    script:
        - cd Data
        - python3.8 gen_svg.py -i ../logs/isp/bench_isp.csv -o isp_result_LOG --header false
        - cp *svg ../logs/
    artifacts:
        untracked: false
        expire_in: 30 days
        when: always
        paths:
            - logs/*

aislinn-svg:
    stage: svg
    needs:
        - job: test-aislinn
          artifacts: true
    # before_script:
    #   - apt-get update
    #   - apt-get install -y python3-pip libcairo2
    #   - pip3 install drawSvg
    script:
        - cd Data
        - python3.8 gen_svg.py -i ../logs/aislinn/bench_aislinn.csv -o aislinn_result_LOG --header false
        - cp *svg ../logs/
    artifacts:
        untracked: false
        expire_in: 30 days
        when: always
        paths:
            - logs/*

civl-svg:
    stage: svg
    needs:
        - job: test-civl-1
          artifacts: true
        - job: test-civl-2
          artifacts: true
        - job: test-civl-3
          artifacts: true
    # before_script:
    #   - apt-get update
    #   - apt-get install -y python3-pip libcairo2
    #   - pip3 install drawSvg
    script:
        - ./scripts/CIVL-run
        - cd Data
        - cat ../logs/civl/*.csv > result.csv
        - python3.8 gen_svg.py -i result.csv -o civl_result_LOG --header false
        - cp *svg ../logs/
    artifacts:
        untracked: false
        expire_in: 30 days
        when: always
        paths:
            - logs/*

must-svg:
    stage: svg
    needs:
        - job: test-must-1
          artifacts: true
        - job: test-must-2
          artifacts: true
        - job: test-must-3
          artifacts: true
        - job: test-must-4
          artifacts: true
        - job: test-must-5
          artifacts: true
        - job: test-must-6
          artifacts: true
        - job: test-must-7
          artifacts: true
        - job: test-must-8
          artifacts: true
        - job: test-must-9
          artifacts: true
        - job: test-must-10
          artifacts: true
    # before_script:
    #   - apt-get update
    #   - apt-get install -y python3-pip libcairo2
    #   - pip3 install drawSvg
    script:
        - ./MBI.py -x must
        - cd Data
        - cat ../logs/must/*.csv > result.csv
        - python3.8 gen_svg.py -i result.csv -o must_result_LOG --header false
        - cp *svg ../logs/
    artifacts:
        untracked: false
        expire_in: 30 days
        when: always
        paths:
            - logs/*

data-collect:
    stage: gather
    needs:
        - job: test-must-1
          artifacts: true
        - job: test-must-2
          artifacts: true
        - job: test-must-3
          artifacts: true
        - job: test-must-4
          artifacts: true
        - job: test-must-5
          artifacts: true
        - job: test-must-6
          artifacts: true
        - job: test-must-7
          artifacts: true
        - job: test-must-8
          artifacts: true
        - job: test-must-9
          artifacts: true
        - job: test-must-10
          artifacts: true
        - job: test-civl-1
          artifacts: true
        - job: test-civl-2
          artifacts: true
        - job: test-civl-3
          artifacts: true
        - job: test-parcoach
          artifacts: true
        - job: test-simgrid
          artifacts: true
        - job: test-isp
          artifacts: true
        - job: test-aislinn
          artifacts: true
        - job: must-svg
          artifacts: true
        - job: civl-svg
          artifacts: true
        - job: parcoach-svg
          artifacts: true
        - job: simgrid-svg
          artifacts: true
        - job: isp-svg
          artifacts: true
        - job: aislinn-svg
          artifacts: true
    # before_script:
    #     - apt-get update
    #     - apt-get install -y python3-pip libcairo2
    #     - pip3 install drawSvg
    script:
        - echo "#filename;id;tool;TO;NP;buff;expected;result;elapsed_time;jobid" > result.csv
        - cd Data
        - cat ../logs/*/*.csv >> result.csv
        - python3.8 gen_svg.py -i result.csv -o all_result_LOG --header true
        - cp *svg ../logs
    artifacts:
        untracked: false
        expire_in: 30 days
        when: always
        paths:
            - logs
